In [12]:
from numpy import array, unique, arange, full, reshape, zeros, ones
import numpy

all_0s = zeros(10)
all_1s = ones(10)
all_5s = full( (1, 10), 5 )

print(all_0s)
print(all_1s)
print(all_5s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[5 5 5 5 5 5 5 5 5 5]]


In [14]:
ten_to_fifty = arange(10, 51)
zero_to_eight = arange(0, 9)
zero_to_eight_square = reshape( zero_to_eight, (3, 3) )

print(ten_to_fifty)
print(zero_to_eight_square)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
from numpy.random import rand, normal
print(rand(1))
print( normal(size = (25,)) )

[0.35020171]
[ 1.39180406 -0.56630882  0.57618044 -0.177592   -0.52753754  2.12574764
 -0.75108465  0.80273802 -0.05081241  1.60564221  0.7518716   0.81141838
 -1.58606168 -1.50962905 -0.9998095  -2.91384809 -1.45629508 -0.92123865
 -1.45938614  1.32648127  0.15884097 -0.51989399 -0.33403612 -1.29602489
 -1.12590773]


In [34]:
print( arange(0.01, 1.01, .01) )

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


In [37]:
from numpy import linspace
print( linspace(0, 1, 20) )

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [54]:
from numpy import arange, reshape
mat = arange(1,26).reshape(5,5)

print( mat[2:5, 1:5] )
print( mat[3, 4] )
print( mat[0:3, 1] )
print( mat[4, 0:5] )
print()
print( mat[3:5, 0:5] )

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
20
[ 2  7 12]
[21 22 23 24 25]

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [58]:
from numpy import sum, std

mat = arange(1,26).reshape(5,5)
print( sum(mat) )
print( sum(mat, axis=0) ) # sum of columns
print( std(mat) ) # standard dev of array

325
[55 60 65 70 75]
7.211102550927978
